#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: JavaScript is not Java

# Short bio or description (displayed in the header)
description: JavaScript is to Java as hamster is to ham.


# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars3.githubusercontent.com/u/3902146?v=3&s=140

navigation:
- title: Home
  url: /index.html
- title: About
  url: /about.html
- title: Examples
  url: /examples.com.html
  layout: post


# Includes an icon in the footer for each username you enter
footer-links:
  email: kaela@kaelanichols.com
  github: kaela
  linkedin: kaelanichols
  #rss: feedstuff # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: kaelanichols
  #stackoverflow: /users/3087765/kaela # your stackoverflow profile, e.g. "users/50476/bart-kiers"

disqus: javascriptisnotjava 
google_analytics: UA-61935120-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://javascriptisnotjava

# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
